### ISSUE TITLE
Deleting other fork ?

### ISSUE THREAD

**Issue by neonsoftware** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#10]
Hi @brian-amos-embedded,

First of all, excellent writing. Not a single line in the book could be removed, each of them contains knowledge, and this efficiency makes it shine among others, please keep writing.

I would like to ask if, to avoid ambiguity, and if it is not explicitly needed, of course, if [this fork](https://github.com/brian-amos-embedded/Hands-On-RTOS-with-Microcontrollers) could be removed from Github (? )

The reason is that I was reading on my tablet and on my PC googled '_brian amos book freertos github_' to download the examples and I ended up on the fork.
Since it is from the author and looks exactly like the upstream, so I didn't blink an eye and used it. 

I encountered the absolute paths issues running on linux so I ended up re-implementing the relative paths and the _.exe_ removal. 
Only when I was preparing to submit a pull-request that I noticed that it was a fork, and that it had all already discussed and fixed months ago in https://github.com/PacktPublishing/Hands-On-RTOS-with-Microcontrollers/issues/2 and  04cf5ecd88b110388f6

I had finished watching the movie Tenet just 30min before so did not mind the accidental time-travel, quite the opposite.

Have an excellent evening

**Comment by brian-amos-embedded** [comment]
Hey there @neonsoftware, 

Thanks a lot for the kind words and the [almost] pull request!  I deleted my errant fork - I'm sure you've saved some other readers (and me) quite a bit of head scratching.  My apologies for the confusion.

Also - I'm adding Tenet to my watchlist now :)

take care,
Brian Amos

**Comment by neonsoftware** [comment]
That was fast, super ! 
I will not hesitate to post any other required adjustments then. 

Typos/errata in the book do not belong here, right ? I will eventually send them to you at the mail provided in other github issues, right ? 

Cheers,
FC

**Comment by brian-amos-embedded** [comment]
It was an easy one ;-)  Feel free to report any text related issues here:
https://www.packtpub.com/support/errata

That will generate an email that will eventually make its way to me, and
the publisher will have a record of the required changes (several have been
submitted already).

Thanks for all the feedback!
