### ISSUE TITLE
Some bugs in Chapter 10

### ISSUE THREAD

**Issue by jimyuill** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#13]
Brian,
I'm continuing to work through your book in depth, and ran across some bugs in Chapter 10.
I documented them in my "study-guide" for the book:
https://jimyuill.com/embedded-systems/study-guide-freertos-book/

BTW: I also ran across some bugs in SEGGER's SystemView, in the API SEGGER_SYSVIEW_PrintfHost().
I described them in the study-guide and reported them to SEGGER.

Again, your book is really good, and I'm learning a lot from it.
It's an impressive amount of work, and esp. if in addition to your day-job.

Sincerely,
Jim Yuill
Greenville, SC

**Comment by brian-amos-embedded** [comment]
Thanks for the reports (and kind words) Jim, I'll look into these next time I'm editing code/text.  The book was definitely a challenge (especially with a full-time job and young family).  I'm very grateful to you for pointing out the issues you're finding in such detail!

**Comment by jimyuill** [comment]
👍
