### ISSUE TITLE
SEGGER SystemView: no probes connected via usb

### ISSUE THREAD

**Issue by JasonDChistensen** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#19]
I was getting "no probes connected via usb" message while using SEGGER SystemView for the first time.  It turns out that installing the JLink drivers (chapter 6 for the Reflash Utility) you need check the box to "Install USB Driver for J-Link".

I consider the issue closed.  I just thought I would report it here in case someone else runs into the same problem.

Jason

**Comment by brian-amos-embedded** [comment]
Thanks for reporting @JasonDChistensen. I'll mark this as closed.
