### ISSUE TITLE
Where to find or how to create STM32F7x7.svd file for new Ozone projects?

### ISSUE THREAD

**Issue by scploeger** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#22]
Thankfully for all exercises in this book, an Ozone project is already provided. However, on page 133 of the textbook (steps for creating an Ozone project for future projects), it mentions to select the STM32F7x7.svd file. Where is this file/how can we create it? Where does it come from?

The .jdebugs (for example, `Chapters5_6.jdebug`) contain: `Project.AddSvdFile ("C:\Program Files (x86)\Atollic\TrueSTUDIO for STM32 9.3.0\ide\plugins\com.atollic.truestudio.tsp.stm32_1.0.0.20190212-0734\tsp\sfr\STM32F7x7.svd");`, however, this is not a path I have on my computer as we are not using TrueStudio.

Thanks!

**Comment by brian-amos-embedded** [comment]
Svd files are basically a description of the register map for a MCU.
They're typically provided by the MCU vendor, usually you can find them
with a "CMSIS pack" distributed by ARM.  Oftentimes they'll also be
included with MCU support packs in an IDE (if you've added support for an
MCU through your IDE, try searching your hard drive for .svd to find the
exact location).  When the book was written, I was initially using True
Studio as the IDE (the path never got updated)

Here's a list of all CMSIS packs from ARM, I'll usually head there first
when setting up tooling for a new MCU.

https://www.keil.arm.com/packs/

**Comment by scploeger** [comment]
Thanks for the reply. I was able to use the solution here to solve the problem! https://github.com/PacktPublishing/Hands-On-RTOS-with-Microcontrollers/issues/9
