### ISSUE TITLE
chapter 7 [main_taskCreation.c] was missing the SEGGER_SYSVIEW_Conf(); 

### ISSUE THREAD

**Issue by brian-amos-embedded** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#7]
chapter 7 [main_taskCreation.c] was missing the SEGGER_SYSVIEW_Conf(); call which made getting a capture with SystemView interesting!

Thanks for the report @G4DCP

**Comment by relayman357** [comment]
Same issue with main_FailedStartup.c

fyi
