### ISSUE TITLE
Build Failures for Chapter5_6 Project

### ISSUE THREAD

**Issue by dsjwork** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#8]
Hi Brian,

The current git clone for this project fails its build because of various include headers files that cannot be found for project Chapter5_6. The other chapters build OK. On further investigation, it appears that the list of include file paths for this project needs to be updated to those of the other chapters. I simply copied the list from C/C++|Build|Settings|Tool Settings|MCU GCC Compiler|Include paths for Chapter_9 to Chapter5_6 etc. This resolved the issue.

Congratulations an an excellent book and debug environment. I have changed over to the Segger way of doing things for FreeRTOS work after reading your book.

Regards
Dave Jones

**Comment by brian-amos-embedded** [comment]
Hi Dave, 

Thanks for the heads up and kind words!

There were a few compilation issues that should have gotten cleaned up a few weeks ago.  I have a few questions, if you don't mind:
- Do you happen to know when you originally cloned the git repo?
- What OS is STM32CubeIDE installed on (there were some linker errors reported under Linux, but not replicated under windows)?

It looks like the main difference between chapters 5-6 and the rest is that the Chapter 5/6 project is using "workspace" includes, whereas the other projects use relative paths.  I'd like to get a better understanding of what works best within Eclipse across different platforms (assuming you have the latest copy of the project).

thanks again,
Brian Amos

**Comment by dsjwork** [comment]
Hi Brian,

 

I am not sure exactly when it was that I did the first clone but it was quite recently. I am guessing in the last week or two. The first clone did build completely as expected without any errors. Give me some time and I will try to work out the date by back tracking through my deleted files. Unfortunately, yesterday, I did a bit of a cleanup of my laptop so I think I may be able to use a recovery tool to get the dates.

 

I am running Windows 10 64-bit and initially used CubeIDE V1.3 where it built OK. I am now using CubeIDE V1.4 which also builds OK as long as the include paths are adjusted. This was after taking a new clone of your repository at about 0630 this morning.

 

Have just got hold of a NUCLEO-F767ZI board so will be able to follow through the book. 

 

Please be sure to let me know if I can help any further.

Regards Dave.

**Comment by dsjwork** [comment]
Hi Brian,

 

I have found another issue that stops Chapter5_main.elf from running correctly both under both CubeIDE and Ozone, however, Chapter7 ran as expected. Haven’t tested the other chapters yet 

 

I did a comparison of the options used for the assembler, compiler and linker for Chapters5_6 and Chapter_7 and found that in the linker settings for each there was a difference in the Linker Script (-T) settings as follows.

 

Chapters5_6

${workspace_loc:/${ProjName}/LinkerScript.ld}

 

Chapter7

../STM32F767ZI_FLASH.ld

 

It appears that LinkerScript.ld does not exist so I don’t know what memory layout we will end up. Oddly, I do not get any build errors saying that it cannot find the file.

 

Anyway using the same setting for Chapters5_6 the project now runs as expected both in CubeIDE and Ozone.

 

It looks that there are other differences too, for example the compiler optimisations are different. I have attached two files that I used to make the comparison. I copied the options for each directly from each project and formatted them by hand to separate each option on a new line.

 

I have a question or two for you if I may and to do with applying the Segger source file patch to the FreeRTOS files for SystemView.

 

I am using SystemView V3.12 and the source files are included with the install (C:\Program Files\SEGGER\SystemView\Src). It includes the patch files that needs to be used to update the FreeRTOS files but my diff tools (DiffMerge and WinMerge both free) do not have no way of applying patches.

 

How did you patch the FreeRTOS files?

 

Were there any additional changes that needed to be made to the FreeRTOS files after they were patched?

 

I was unable to find the exact date that I did my first clone, sorry about that!

 

Hoping this assists you.

 

Regards

Dave.

**Comment by brian-amos-embedded** [comment]
Hi Dave,

Thanks for the comparison.

The project files were originally created with Atollic True Studio and
later converted to STMCubeIDE. Chapter5-6 did not import into the newer
Cube IDE properly, which might account for some of the differences. I'm not
sure why you're running into build issues.  I've been compiling from a
fresh git clone and eclipse workspace without any errors or warnings.  When
I'm near my development system, I'll look into the linker file issue.

The patches were applied using a port of gnu diff for windows.  The patch
files I used did not apply cleanly, so some files were hand patched.

-Brian
